[phases.setup]
nixPkgs = ["python39", "nodejs", "npm"]

[phases.install]
cmds = [
  "cd backend && pip install -r requirements.txt",
  "cd ../frontend && npm ci"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd backend && python app.py"
