services:
  - type: web
    name: asteroid-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NASA_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: FLASK_ENV
        value: production
